# Generated by Django 2.2.1 on 2019-05-05 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mine_name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': '试验矿井名称',
                'verbose_name_plural': '试验矿井名称',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=256, verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '项目名称',
                'verbose_name_plural': '项目名称',
            },
        ),
        migrations.CreateModel(
            name='MineDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_role', models.CharField(max_length=256, verbose_name='项目作用')),
                ('mine_gas_grade', models.CharField(choices=[('煤与瓦斯突出矿井', '煤与瓦斯突出矿井'), ('高瓦斯矿井', '高瓦斯矿井'), ('低瓦斯矿井', '低瓦斯矿井')], max_length=256, verbose_name='矿井瓦斯等级')),
                ('work_instruction_document', models.FilePathField(verbose_name='作业指导文件')),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Mine')),
            ],
            options={
                'verbose_name': '试验矿井详情',
                'verbose_name_plural': '试验矿井详情',
            },
        ),
        migrations.AddField(
            model_name='mine',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Project'),
        ),
    ]
