# Generated by Django 2.2.1 on 2019-05-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minedetail',
            name='mine_gas_grade',
        ),
        migrations.RemoveField(
            model_name='minedetail',
            name='work_instruction_document',
        ),
    ]
