# Generated by Django 2.2.1 on 2019-05-05 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190505_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='minedetail',
            name='mine_status',
            field=models.CharField(default='空', max_length=256, verbose_name='矿井状态'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='mine_name',
            field=models.CharField(max_length=256, verbose_name='矿井名称'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Project', verbose_name='项目名称'),
        ),
    ]
