# Generated by Django 2.2.1 on 2019-05-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20190505_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='minedetail',
            name='mine_gas_grade',
            field=models.CharField(choices=[('hybrid', '煤与瓦斯突出矿井'), ('hign', '高瓦斯矿井'), ('low', '低瓦斯矿井')], default='low', max_length=256, verbose_name='矿井瓦斯等级'),
        ),
    ]
