# Generated by Django 2.2.1 on 2019-05-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20190505_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minedetail',
            name='work_instruction_document',
            field=models.FileField(blank=True, upload_to='upload/%Y/%m/%d/%H/%M/%s', verbose_name='作业指导文件'),
        ),
    ]
