# Generated by Django 2.2.1 on 2019-05-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20190506_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minedetail',
            name='coal_seam_occurrence',
            field=models.CharField(default='', max_length=256, verbose_name='煤层赋存'),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='geological_condition',
            field=models.CharField(default='', max_length=256, verbose_name='地质条件'),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='mine_status',
            field=models.CharField(default='', max_length=256, verbose_name='矿井状态'),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='mining_order_method_process',
            field=models.CharField(default='', max_length=256, verbose_name='开采顺序、方法、工艺'),
        ),
    ]
