# Generated by Django 2.2.1 on 2019-05-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20190506_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='minedetail',
            name='gas_storage',
            field=models.CharField(default='', max_length=256, verbose_name='瓦斯赋存'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='staff_composition_quality',
            field=models.CharField(default='', max_length=256, verbose_name='人员构成及素质'),
        ),
    ]
