# Generated by Django 2.2.1 on 2019-05-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20190506_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='minedetail',
            name='impact_on_mine_production_system',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='对矿井生产系统布局和采掘施工的影响'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='implementation_period',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='实施工期'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='operating_procedure',
            field=models.FileField(blank=True, upload_to='upload/%Y/%m/%d/%H/%M/%S', verbose_name='操作规程'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='process_adaptation_conditions',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='工艺适应条件'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='staff_technical_foundation',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='人的技术基础'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='technical_complexity',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='技术复杂程度'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='technical_description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='技术描述'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='whether_it_is_necessary',
            field=models.CharField(blank=True, choices=[('是', '是'), ('否', '否')], default='是', max_length=256, verbose_name='是否需分别在煤、岩层中施工'),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='coal_seam_occurrence',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='煤层赋存'),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='gas_storage',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='瓦斯赋存'),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='geological_condition',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='地质条件'),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='mine_gas_grade',
            field=models.CharField(blank=True, choices=[('hybrid', '煤与瓦斯突出矿井'), ('hign', '高瓦斯矿井'), ('low', '低瓦斯矿井')], default='low', max_length=256, verbose_name='矿井瓦斯等级'),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='mine_status',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='矿井状态'),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='mining_order_method_process',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='开采顺序、方法、工艺'),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='project_role',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='项目作用'),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='staff_composition_quality',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='人员构成及素质'),
        ),
        migrations.AlterField(
            model_name='minedetail',
            name='work_instruction_document',
            field=models.FileField(blank=True, upload_to='upload/%Y/%m/%d/%H/%M/%S', verbose_name='作业指导文件'),
        ),
    ]
