# Generated by Django 2.2.1 on 2019-05-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20190506_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='minedetail',
            name='job_control_program',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='作业控制程序'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='management_responsibility',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='管理职责'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='组织机构'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='quantitative_effect_achieved',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='达到的量化效果'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='quantity_of_work',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='工程量'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='resource_matching',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='资源配套'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='technical_characteristics',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='技术特征'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='technical_process_control_document',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='技术过程控制文件'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='the_best_technical_indicators_and_standards',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='达到的最佳技术指标及标准'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='the_best_time_standard',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='完成效果的最佳时间标准'),
        ),
        migrations.AddField(
            model_name='minedetail',
            name='work_link',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='工作环节'),
        ),
    ]
